#https://gist.github.com/michaelneu/2ca7987ef00fa3fbe4fd7b9c07834cc7
version: '3'
services:
  web8700:
    image: nginx:1.14.0
    ports:
      - "8700:80"
    # uncomment port 443 for https
    # - "443:443"
    container_name: web8700 
    volumes:
      - ./code:/code
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl/certs:/etc/nginx/ssl/certs
    links:
      - php9700
  php9700:
    build: 
      context: .
      dockerfile: Dockerfile.7.0-fpm
    volumes: 
      - ./code:/code
    image: php9700:7.0-fpm
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    links:
      - mysql5.6-3376
      - maildev8790
  mysql5.6-3376:
    image: mysql:5.6
    volumes:
      - mysql5.6-3376:/var/lib/mysql
    container_name: mysql5.6-3376 
    ports:
      - "3376:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin8780:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql5.6-3376:db
    ports:
      - "8780:80"
    container_name: phpmyadmin8780 
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PHP_UPLOAD_MAX_FILESIZE=100MB
  maildev8790:
    image: djfarrelly/maildev
    container_name: maildev8790 
    ports:
     - "8790:80"
volumes:
  mysql5.6-3376:
